<?php

namespace Database\Seeders;

use App\Models\FacilityReservation;
use Illuminate\Database\Seeder;

class FacilityReservationSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            // 1. Pesan Diterima — just submitted, paid
            [
                'nomor'             => 'FRS10000008/V/2026-MAP',
                'unit'              => 'MP/15/FK',
                'tenant_name'       => 'BUDI SANTOSO',
                'nama_fasilitas'    => 'Balai Warga',
                'tanggal_reservasi' => '2026-06-07',
                'jam_mulai'         => '18:00:00',
                'jam_selesai'       => '22:00:00',
                'keperluan'         => 'Acara ulang tahun anak',
                'jumlah_tamu'       => 60,
                'is_berbayar'       => true,
                'biaya'             => 500000,
                'status_bayar'      => 'Belum Bayar',
                'status'            => 'Pesan Diterima',
                'request_by'        => 'BUDI SANTOSO (Pemilik)',
                'request_via'       => 'WhatsApp',
            ],
            // 2. Disetujui CS — paid, CS done, Finance pending, HK done, ENG pending
            [
                'nomor'             => 'FRS10000007/V/2026-MAP',
                'unit'              => 'MP/29/AB',
                'tenant_name'       => 'BANEDGAR WIRATAMA CUNG',
                'nama_fasilitas'    => 'Function Room',
                'tanggal_reservasi' => '2026-05-30',
                'jam_mulai'         => '09:00:00',
                'jam_selesai'       => '17:00:00',
                'keperluan'         => 'Meeting kantor',
                'jumlah_tamu'       => 20,
                'is_berbayar'       => true,
                'biaya'             => 750000,
                'status_bayar'      => 'Belum Bayar',
                'status'            => 'Disetujui CS',
                'request_by'        => 'BANEDGAR WIRATAMA CUNG (Penyewa)',
                'request_via'       => 'aplikasi',
                'cs_by'             => 'CS Duty',
                'cs_at'             => '2026-05-24 10:00:00',
                'hk_by'             => 'HK Duty',
                'hk_at'             => '2026-05-24 14:00:00',
            ],
            // 3. Disetujui CS — FREE, CS done, HK pending, ENG done
            [
                'nomor'             => 'FRS10000006/V/2026-MAP',
                'unit'              => 'MP/5/BV',
                'tenant_name'       => 'FILVANAWATY',
                'nama_fasilitas'    => 'Gym / Fitness Center',
                'tanggal_reservasi' => '2026-05-27',
                'jam_mulai'         => '07:00:00',
                'jam_selesai'       => '09:00:00',
                'keperluan'         => 'Olahraga rutin pagi',
                'jumlah_tamu'       => 3,
                'is_berbayar'       => false,
                'biaya'             => 0,
                'status_bayar'      => 'Bebas Biaya',
                'status'            => 'Disetujui CS',
                'request_by'        => 'FILVANAWATY (Penyewa)',
                'request_via'       => 'aplikasi',
                'cs_by'             => 'CS Duty',
                'cs_at'             => '2026-05-25 08:00:00',
                'eng_by'            => 'ENG Duty',
                'eng_at'            => '2026-05-25 09:00:00',
            ],
            // 4. Disetujui CS — paid, CS + Finance confirmed, HK + ENG pending (NOT yet Siap)
            [
                'nomor'             => 'FRS10000005/V/2026-MAP',
                'unit'              => 'MP/12/CD',
                'tenant_name'       => 'ANDI PRATAMA',
                'nama_fasilitas'    => 'Balai Warga',
                'tanggal_reservasi' => '2026-05-28',
                'jam_mulai'         => '19:00:00',
                'jam_selesai'       => '23:00:00',
                'keperluan'         => 'Syukuran pernikahan',
                'jumlah_tamu'       => 80,
                'is_berbayar'       => true,
                'biaya'             => 500000,
                'status_bayar'      => 'Sudah Bayar',
                'status'            => 'Disetujui CS',
                'request_by'        => 'ANDI PRATAMA (Pemilik)',
                'request_via'       => 'Visit',
                'cs_by'             => 'CS Duty',
                'cs_at'             => '2026-05-22 10:30:00',
                'fin_by'            => 'Finance Officer',
                'fin_at'            => '2026-05-23 11:00:00',
            ],
            // 5. Siap Pelaksanaan — paid, all checks done
            [
                'nomor'             => 'FRS10000004/V/2026-MAP',
                'unit'              => 'MP/8/AH',
                'tenant_name'       => 'SITI RAHAYU',
                'nama_fasilitas'    => 'Rooftop Garden',
                'tanggal_reservasi' => '2026-05-25',
                'jam_mulai'         => '16:00:00',
                'jam_selesai'       => '20:00:00',
                'keperluan'         => 'Gathering keluarga',
                'jumlah_tamu'       => 25,
                'is_berbayar'       => true,
                'biaya'             => 200000,
                'status_bayar'      => 'Sudah Bayar',
                'status'            => 'Siap Pelaksanaan',
                'request_by'        => 'SITI RAHAYU (Penyewa)',
                'request_via'       => 'WhatsApp',
                'cs_by'             => 'CS Duty',
                'cs_at'             => '2026-05-20 09:00:00',
                'fin_by'            => 'Finance Officer',
                'fin_at'            => '2026-05-20 14:00:00',
                'hk_by'             => 'HK Duty',
                'hk_at'             => '2026-05-25 14:00:00',
                'eng_by'            => 'ENG Duty',
                'eng_at'            => '2026-05-25 15:00:00',
            ],
            // 6. Sedang Berlangsung — FREE, all done, SEC opened
            [
                'nomor'             => 'FRS10000003/V/2026-MAP',
                'unit'              => 'MP/23/BK',
                'tenant_name'       => 'DEVINA',
                'nama_fasilitas'    => 'Kolam Renang',
                'tanggal_reservasi' => '2026-05-25',
                'jam_mulai'         => '08:00:00',
                'jam_selesai'       => '10:00:00',
                'keperluan'         => 'Renang bersama anak',
                'jumlah_tamu'       => 4,
                'is_berbayar'       => false,
                'biaya'             => 0,
                'status_bayar'      => 'Bebas Biaya',
                'status'            => 'Sedang Berlangsung',
                'request_by'        => 'DEVINA (Penyewa)',
                'request_via'       => 'aplikasi',
                'cs_by'             => 'CS Duty',
                'cs_at'             => '2026-05-24 16:00:00',
                'hk_by'             => 'HK Duty',
                'hk_at'             => '2026-05-25 07:00:00',
                'eng_by'            => 'ENG Duty',
                'eng_at'            => '2026-05-25 07:30:00',
                'sec_open_by'       => 'Security Duty',
                'sec_open_at'       => '2026-05-25 08:00:00',
            ],
            // 7. Selesai — paid, fully completed
            [
                'nomor'             => 'FRS10000002/V/2026-MAP',
                'unit'              => 'MP/3/AC',
                'tenant_name'       => 'HARTONO WIBOWO',
                'nama_fasilitas'    => 'BBQ Area',
                'tanggal_reservasi' => '2026-05-20',
                'jam_mulai'         => '17:00:00',
                'jam_selesai'       => '21:00:00',
                'keperluan'         => 'BBQ bersama teman',
                'jumlah_tamu'       => 15,
                'is_berbayar'       => true,
                'biaya'             => 150000,
                'status_bayar'      => 'Sudah Bayar',
                'status'            => 'Selesai',
                'request_by'        => 'HARTONO WIBOWO (Pemilik)',
                'request_via'       => 'Phone',
                'cs_by'             => 'CS Duty',
                'cs_at'             => '2026-05-18 10:00:00',
                'fin_by'            => 'Finance Officer',
                'fin_at'            => '2026-05-18 15:00:00',
                'hk_by'             => 'HK Duty',
                'hk_at'             => '2026-05-20 16:00:00',
                'eng_by'            => 'ENG Duty',
                'eng_at'            => '2026-05-20 16:30:00',
                'sec_open_by'       => 'Security Duty',
                'sec_open_at'       => '2026-05-20 17:00:00',
                'sec_close_by'      => 'Security Duty',
                'sec_close_at'      => '2026-05-20 21:15:00',
                'sec_close_catatan' => 'Ruangan dalam kondisi baik. Semua peralatan sudah dikembalikan.',
            ],
            // 8. Ditolak — rejected by CS
            [
                'nomor'             => 'FRS10000001/V/2026-MAP',
                'unit'              => 'MP/7/BF',
                'tenant_name'       => 'DIAN PURNAMA',
                'nama_fasilitas'    => 'Mini Theater',
                'tanggal_reservasi' => '2026-05-15',
                'jam_mulai'         => '14:00:00',
                'jam_selesai'       => '17:00:00',
                'keperluan'         => 'Nobar film',
                'jumlah_tamu'       => 30,
                'is_berbayar'       => true,
                'biaya'             => 300000,
                'status_bayar'      => 'Belum Bayar',
                'status'            => 'Ditolak',
                'request_by'        => 'DIAN PURNAMA (Penyewa)',
                'request_via'       => 'WhatsApp',
                'catatan'           => 'Ditolak: data hunian tidak valid, unit dalam proses over-stay.',
            ],
        ];

        foreach ($records as $record) {
            FacilityReservation::create($record);
        }
    }
}
