<?php

namespace Database\Seeders;

use App\Models\InOutPermit;
use Illuminate\Database\Seeder;

class InOutPermitSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'nomor'          => 'KMB10000309/V/2026-MAP',
                'unit'           => 'MP/29/AB',
                'tenant_name'    => null,
                'tanggal'        => '2026-05-25',
                'tanggal_ijin'   => '2026-05-25',
                'jam'            => '14:15:00',
                'jenis'          => 'Masuk',
                'descs'          => 'Masuk Tv di unit 29ab',
                'request_by'     => 'BANEDGAR WIRATAMA CUNG (Penyewa)',
                'request_via'    => 'aplikasi',
                'status'         => 'Approve by Customer Service',
                'approved_cs_by' => 'CS Duty',
                'approved_cs_at' => '2026-05-25 14:30:00',
            ],
            [
                'nomor'          => 'KMB10000308/V/2026-MAP',
                'unit'           => 'MP/5/BV',
                'tenant_name'    => 'FILVANAWATY',
                'tanggal'        => '2026-05-23',
                'tanggal_ijin'   => '2026-05-23',
                'jam'            => '13:11:00',
                'jenis'          => 'Masuk',
                'descs'          => 'sofa',
                'request_by'     => 'FILVANAWATY',
                'request_via'    => 'aplikasi',
                'status'         => 'Approve by Customer Service',
                'approved_cs_by' => 'CS Duty',
                'approved_cs_at' => '2026-05-23 13:20:00',
            ],
            [
                'nomor'          => 'KMB10000307/V/2026-MAP',
                'unit'           => 'MP/5/BV',
                'tenant_name'    => 'FILVANAWATY',
                'tanggal'        => '2026-05-23',
                'tanggal_ijin'   => '2026-05-23',
                'jam'            => '13:11:00',
                'jenis'          => 'Masuk',
                'descs'          => 'rak sepatu',
                'request_by'     => 'FILVANAWATY',
                'request_via'    => 'aplikasi',
                'status'         => 'Approve by Customer Service',
                'approved_cs_by' => 'CS Duty',
                'approved_cs_at' => '2026-05-23 13:20:00',
            ],
            [
                'nomor'          => 'KMB10000306/V/2026-MAP',
                'unit'           => 'MP/5/BV',
                'tenant_name'    => 'FILVANAWATY',
                'tanggal'        => '2026-05-23',
                'tanggal_ijin'   => '2026-05-23',
                'jam'            => '13:11:00',
                'jenis'          => 'Masuk',
                'descs'          => 'rak tv',
                'request_by'     => 'FILVANAWATY',
                'request_via'    => 'aplikasi',
                'status'         => 'Approve by Customer Service',
                'approved_cs_by' => 'CS Duty',
                'approved_cs_at' => '2026-05-23 13:20:00',
            ],
            [
                'nomor'          => 'KMB10000305/V/2026-MAP',
                'unit'           => 'MP/23/BK',
                'tenant_name'    => null,
                'tanggal'        => '2026-05-23',
                'tanggal_ijin'   => '2026-05-23',
                'jam'            => '11:59:00',
                'jenis'          => 'Keluar',
                'descs'          => 'Kulkas mini',
                'request_by'     => 'DEVINA (Penyewa)',
                'request_via'    => 'aplikasi',
                'status'         => 'Pesan Diterima',
            ],
            [
                'nomor'          => 'KMB10000304/V/2026-MAP',
                'unit'           => 'MP/23/BK',
                'tenant_name'    => null,
                'tanggal'        => '2026-05-23',
                'tanggal_ijin'   => '2026-05-23',
                'jam'            => '11:59:00',
                'jenis'          => 'Keluar',
                'descs'          => 'Kulkas mini',
                'request_by'     => 'DEVINA (Penyewa)',
                'request_via'    => 'aplikasi',
                'status'         => 'Pesan Diterima',
            ],
            [
                'nomor'          => 'KMB10000303/V/2026-MAP',
                'unit'           => 'MP/23/BK',
                'tenant_name'    => null,
                'tanggal'        => '2026-05-23',
                'tanggal_ijin'   => '2026-05-23',
                'jam'            => '11:59:00',
                'jenis'          => 'Keluar',
                'descs'          => 'Kulkas mini',
                'request_by'     => 'DEVINA (Penyewa)',
                'request_via'    => 'aplikasi',
                'status'         => 'Pesan Diterima',
            ],
            [
                'nomor'          => 'KMB10000302/V/2026-MAP',
                'unit'           => 'MP/12/CD',
                'tenant_name'    => 'ANDI PRATAMA',
                'tanggal'        => '2026-05-22',
                'tanggal_ijin'   => '2026-05-22',
                'jam'            => '10:00:00',
                'jenis'          => 'Masuk',
                'descs'          => 'Mesin cuci',
                'request_by'     => 'ANDI PRATAMA (Pemilik)',
                'request_via'    => 'WhatsApp',
                'status'         => 'Approve by FA',
                'approved_cs_by' => 'CS Duty',
                'approved_cs_at' => '2026-05-22 10:30:00',
                'approved_fa_by' => 'FA Officer',
                'approved_fa_at' => '2026-05-22 11:00:00',
            ],
            [
                'nomor'          => 'KMB10000301/V/2026-MAP',
                'unit'           => 'MP/8/AH',
                'tenant_name'    => 'SITI RAHAYU',
                'tanggal'        => '2026-05-21',
                'tanggal_ijin'   => '2026-05-21',
                'jam'            => '09:30:00',
                'jenis'          => 'Keluar',
                'descs'          => 'Lemari pakaian 2 pintu',
                'request_by'     => 'SITI RAHAYU (Penyewa)',
                'request_via'    => 'Visit',
                'status'         => 'Approve by Security',
                'approved_cs_by' => 'CS Duty',
                'approved_cs_at' => '2026-05-21 09:45:00',
                'approved_fa_by' => 'FA Officer',
                'approved_fa_at' => '2026-05-21 10:00:00',
                'approved_sec_by'=> 'Security Duty',
                'approved_sec_at'=> '2026-05-21 10:30:00',
            ],
            [
                'nomor'          => 'KMB10000300/V/2026-MAP',
                'unit'           => 'MP/15/FK',
                'tenant_name'    => 'BUDI SANTOSO',
                'tanggal'        => '2026-05-20',
                'tanggal_ijin'   => '2026-05-20',
                'jam'            => '14:00:00',
                'jenis'          => 'Keluar',
                'descs'          => 'Sepeda motor (STNK terlampir)',
                'request_by'     => 'BUDI SANTOSO (Penyewa)',
                'request_via'    => 'Phone',
                'status'         => 'Tidak Disetujui',
            ],
        ];

        foreach ($records as $record) {
            InOutPermit::create($record);
        }
    }
}
