<?php

namespace Database\Seeders;

use App\Models\TenantRequest;
use Illuminate\Database\Seeder;

class TenantRequestSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'no_request'   => 'R1002870/V/2026-MAP',
                'tanggal'      => '2026-05-20 09:00:00',
                'tgl_verifikasi' => '2026-05-20',
                'lot_no'       => 'MP/18/AN',
                'nama'         => 'RIZKY PRATAMA',
                'kepemilikan'  => 'Owner',
                'sales_agent'  => 'ANDI',
                'kategori'     => 'Unit Rumah/Ruko',
                'sub_kategori' => 'GENERAL',
                'pelaporan_via'=> 'WhatsApp',
                'descs'        => 'Saluran air dapur tersumbat, tidak bisa mengalir.',
                'request_by'   => 'RIZKY PRATAMA',
                'status'       => 'Selesai',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-19',
                'desc_status'  => "WO dibuat\nSelesai dikerjakan",
                'input_by'     => 'yella',
                'is_selesai'   => true,
            ],
            [
                'no_request'   => 'R1002885/V/2026-MAP',
                'tanggal'      => '2026-05-21 13:30:00',
                'tgl_verifikasi' => '2026-05-21',
                'lot_no'       => 'MP/35/B',
                'nama'         => 'DEWI SUSANTI',
                'kepemilikan'  => 'Owner',
                'sales_agent'  => 'BUDI',
                'kategori'     => 'Unit Rumah/Ruko',
                'sub_kategori' => 'HVAC',
                'pelaporan_via'=> 'Phone',
                'descs'        => 'AC split 1.5 PK tidak dingin, sudah dicoba ganti filter tapi tetap.',
                'request_by'   => 'DEWI SUSANTI',
                'status'       => 'Dalam Pengecekan',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-20',
                'desc_status'  => 'WO EX02985 dibuat',
                'input_by'     => 'adit',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002887/V/2026-MAP',
                'tanggal'      => '2026-05-22 08:00:00',
                'tgl_verifikasi' => null,
                'lot_no'       => 'MP/45/CD',
                'nama'         => 'LINA MARLINA',
                'kepemilikan'  => 'Tenant',
                'sales_agent'  => 'CANDRA',
                'kategori'     => 'Unit Rumah/Ruko',
                'sub_kategori' => 'PAINTING',
                'pelaporan_via'=> 'Email',
                'descs'        => 'Dinding ruang tamu mengelupas cat, perlu dicat ulang.',
                'request_by'   => 'LINA MARLINA',
                'status'       => 'Pesan Diterima',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-15',
                'desc_status'  => 'WO EX02987 dibuat',
                'input_by'     => 'adit',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002888/V/2026-MAP',
                'tanggal'      => '2026-05-22 10:30:00',
                'tgl_verifikasi' => null,
                'lot_no'       => 'MP/12/C',
                'nama'         => 'BUDI SANTOSO',
                'kepemilikan'  => 'Owner',
                'sales_agent'  => 'ANDI',
                'kategori'     => 'Unit Rumah/Ruko',
                'sub_kategori' => 'PLUMBING',
                'pelaporan_via'=> 'WhatsApp',
                'descs'        => 'Pipa air kamar mandi utama bocor, sudah 2 hari.',
                'request_by'   => 'BUDI SANTOSO',
                'status'       => 'Dalam Proses',
                'berulang'     => 'Ya',
                'tgl_str'      => '2026-05-21',
                'desc_status'  => 'WO EX02988 dibuat',
                'input_by'     => 'adit',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002889/V/2026-MAP',
                'tanggal'      => '2026-05-22 11:45:00',
                'tgl_verifikasi' => '2026-05-22',
                'lot_no'       => 'MP/06/BA',
                'nama'         => 'MELY YANTI',
                'kepemilikan'  => 'Tenant',
                'sales_agent'  => 'RINA',
                'kategori'     => 'Access Card',
                'sub_kategori' => 'ACCESS CARD',
                'pelaporan_via'=> 'Phone',
                'descs'        => 'Access card rusak, perlu pemblokiran dan pembuatan baru.',
                'request_by'   => 'MELY YANTI',
                'status'       => 'Dalam Pengecekan',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-22',
                'desc_status'  => 'WO EX02989 dibuat',
                'input_by'     => 'yella',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002890/V/2026-MAP',
                'tanggal'      => '2026-05-22 11:55:00',
                'tgl_verifikasi' => null,
                'lot_no'       => 'MP/29/AN',
                'nama'         => 'ANNIE DARMAWAN',
                'kepemilikan'  => 'Owner',
                'sales_agent'  => 'ANDI',
                'kategori'     => 'Unit Rumah/Ruko',
                'sub_kategori' => 'CIVIL',
                'pelaporan_via'=> 'WhatsApp',
                'descs'        => 'Nat kamar mandi retak dan plafond unit bawah perlu perapihan.',
                'request_by'   => 'ANNIE DARMAWAN',
                'status'       => 'Dalam Pengecekan',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-20',
                'desc_status'  => 'WO EX02990 dibuat',
                'input_by'     => 'yella',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002891/V/2026-MAP',
                'tanggal'      => '2026-05-22 14:00:00',
                'tgl_verifikasi' => null,
                'lot_no'       => 'MP/08/BC',
                'nama'         => 'HENDRA WIJAYA',
                'kepemilikan'  => 'Owner',
                'sales_agent'  => 'BUDI',
                'kategori'     => 'Unit Rumah/Ruko',
                'sub_kategori' => 'ELECTRICAL',
                'pelaporan_via'=> 'Visit',
                'descs'        => 'Lampu kamar tidur utama berkedip dan MCB sering trip.',
                'request_by'   => 'HENDRA WIJAYA',
                'status'       => 'Pesan Diterima',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-22',
                'desc_status'  => 'Menunggu jadwal pengecekan',
                'input_by'     => 'adit',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002892/V/2026-MAP',
                'tanggal'      => '2026-05-22 15:30:00',
                'tgl_verifikasi' => null,
                'lot_no'       => 'MP/55/A',
                'nama'         => 'SUSI WULANDARI',
                'kepemilikan'  => 'Tenant',
                'sales_agent'  => 'CANDRA',
                'kategori'     => 'Lift / Elevator',
                'sub_kategori' => 'LIFT',
                'pelaporan_via'=> 'WhatsApp',
                'descs'        => 'Lift Tower A sering berhenti di lantai 5 dan pintu tidak mau buka.',
                'request_by'   => 'SUSI WULANDARI',
                'status'       => 'Dalam Pengecekan',
                'berulang'     => 'Ya',
                'tgl_str'      => '2026-05-18',
                'desc_status'  => "Sudah dicek vendor\nMenunggu spare part",
                'input_by'     => 'yella',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002893/V/2026-MAP',
                'tanggal'      => '2026-05-23 08:15:00',
                'tgl_verifikasi' => null,
                'lot_no'       => 'MP/22/CD',
                'nama'         => 'TOMMY HALIM',
                'kepemilikan'  => 'Owner',
                'sales_agent'  => 'RINA',
                'kategori'     => 'Air & Listrik',
                'sub_kategori' => 'WATER / ELECTRICITY',
                'pelaporan_via'=> 'Phone',
                'descs'        => 'Meteran air tidak terbaca, kran air menetes terus meski sudah ditutup.',
                'request_by'   => 'TOMMY HALIM',
                'status'       => 'Pesan Diterima',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-22',
                'desc_status'  => 'Pesan diterima, belum dijadwalkan',
                'input_by'     => 'adit',
                'is_selesai'   => false,
            ],
            [
                'no_request'   => 'R1002894/V/2026-MAP',
                'tanggal'      => '2026-05-23 09:45:00',
                'tgl_verifikasi' => null,
                'lot_no'       => 'MP/11/AB',
                'nama'         => 'DIANA KUSUMA',
                'kepemilikan'  => 'Owner',
                'sales_agent'  => 'ANDI',
                'kategori'     => 'Fasilitas Umum',
                'sub_kategori' => 'GENERAL',
                'pelaporan_via'=> 'aplikasi',
                'descs'        => 'Kolam renang lantai GF kotor dan pompa air kolam berbunyi keras.',
                'request_by'   => 'DIANA KUSUMA',
                'status'       => 'Pesan Diterima',
                'berulang'     => 'Tidak',
                'tgl_str'      => '2026-05-23',
                'desc_status'  => 'Pesan diterima',
                'input_by'     => 'adit',
                'is_selesai'   => false,
            ],
        ];

        foreach ($records as $record) {
            TenantRequest::create($record);
        }
    }
}
